version: '3.0'

services:
  localstack:
    image: localstack/localstack:latest
    environment:
      - SERVICES=sqs,sns
      - AWS_DEFAULT_REGION=eu-central-1
      - EDGE_PORT=4567
    ports:
      - '4567-4598:4567-4598'
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

  test-env:
    build: .
    tty: true
    ports:
      - "8003:8003"